name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build JavaScript artifacts
        run: |
          deno install
          deno task bundle
      - name: Build Python artifacts
        run: |
          python -m pip install -U build
          python -m build
      - name: Create GitHub Release
        env:
          TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${TAG} \
            --title "yt-dlp-ejs ${TAG}" \
            --notes-from-tag \
            --verify-tag \
            dist/yt.solver.*.js \
            dist/yt_dlp_ejs-*.whl \
            dist/yt_dlp_ejs-*.tar.gz
